[defender]
# sede-dvl-apl1 ansible_host=172.17.62.114
# sede-dvl-bd1 ansible_host=172.17.62.116
sede-dvl-dkr1 ansible_host=172.17.62.156
# sede-dvl-glzb1 ansible_host=172.17.62.109
# sede-dvl-intra1 ansible_host=172.17.62.26
sede-dvl-invti ansible_host=172.17.62.244
sede-dvl-kubedevm01 ansible_host=172.17.62.197
sede-dvl-kubedevm02 ansible_host=172.17.62.203
sede-dvl-kubedevm03 ansible_host=172.17.62.204
sede-dvl-kubedevw01 ansible_host=172.17.62.207
sede-dvl-kubedevw02 ansible_host=172.17.62.208
sede-dvl-kubedevw03 ansible_host=172.17.62.219
sede-dvl-kubew04 ansible_host=172.17.62.128
sede-dvl-kubew05 ansible_host=172.17.62.119
sede-dvl-lec ansible_host=172.17.62.206
sede-dvl-minio1 ansible_host=172.17.62.168
sede-dvl-noh1 ansible_host=172.17.62.243
sede-dvl-sol1 ansible_host=172.17.62.28
# sede-dvl-tomcat ansible_host=172.17.62.181
sede-dvl-tomcat-monolitico ansible_host=172.17.62.193
# sede-hvl-cglpi1 ansible_host=172.17.62.179
sede-hvl-pac1 ansible_host=172.17.62.225
# sede-hvl-pg1 ansible_host=172.17.62.16
sede-hvl-tcat1 ansible_host=172.17.62.141
sede-hvl-tcat2 ansible_host=172.17.62.5
sede-hv-postgresql ansible_host=172.17.62.240
sede-hv-wildfly ansible_host=172.17.62.241
# sede-pvl-autgzb ansible_host=172.17.62.68
# sede-tvl-apl1 ansible_host=172.17.62.73
sede-tvl-appsei ansible_host=172.17.62.172
sede-tvl-mysqorp ansible_host=172.17.62.142
sede-vdl-conhecimento1 ansible_host=172.17.62.242
sede-vdl-glog ansible_host=172.17.62.108
sede-vd-pgaghu1 ansible_host=172.17.62.53
sede-vd-phpipam ansible_host=172.17.62.113
sede-vd-reds01 ansible_host=172.17.62.59
sede-vd-reds02 ansible_host=172.17.62.60
sede-vd-siaudi1 ansible_host=172.17.62.145
sede-vd-sig1 ansible_host=172.17.62.29
sede-vd-sigl1 ansible_host=172.17.62.201
sede-tvl-pg1 ansible_host=172.17.62.105
sede-tvl-pg2 ansible_host=172.17.62.106
sede-tvl-redmne3 ansible_host=172.17.62.19
sede-vd-aghu1 ansible_host=172.17.62.61
sede-vd-apisig1 ansible_host=172.17.62.17
sede-vd-biaghu1 ansible_host=172.17.62.45
sede-vd-cards ansible_host=172.17.62.166
sede-vd-cldb01 ansible_host=172.17.62.183
# sede-vd-cldb02 ansible_host=172.17.62.184
# sede-vd-cldb03 ansible_host=172.17.62.185
# sede-vd-cldb04 ansible_host=172.17.62.186
sede-vd-dev4 ansible_host=172.17.62.232
sede-vd-edc1 ansible_host=172.17.62.25
sede-vd-glpirt ansible_host=172.17.62.84
sede-vd-gotodata ansible_host=172.17.62.9
sede-vd-gpc01 ansible_host=172.17.62.196
sede-vd-haglpi ansible_host=172.17.62.144
sede-vd-labcbds ansible_host=172.17.62.36
# sede-vdl-bicorp ansible_host=172.17.62.142
sede-vdl-conhecimento1 ansible_host=172.17.62.242
sede-vdl-glog ansible_host=172.17.62.108
sede-vd-pgaghu1 ansible_host=172.17.62.53
sede-vd-phpipam ansible_host=172.17.62.113
sede-vd-reds01 ansible_host=172.17.62.59
sede-vd-reds02 ansible_host=172.17.62.60
sede-vd-siaudi1 ansible_host=172.17.62.145
sede-vd-sig1 ansible_host=172.17.62.29
sede-vd-sig2 ansible_host=172.17.62.8
sede-vd-sigapi ansible_host=172.17.62.220
sede-vd-simec2 ansible_host=172.17.62.200
sede-vd-simec3 ansible_host=172.17.62.111
sede-vd-sisfamapp ansible_host=172.17.62.228
sede-vd-sisfamdb ansible_host=172.17.62.227
sede-vd-stt01 ansible_host=172.17.62.249
sede-vd-stt02 ansible_host=172.17.62.248
sede-vd-stt03 ansible_host=172.17.62.247
sede-vd-stt04 ansible_host=172.17.62.246
sede-vd-stt06 ansible_host=172.17.62.43
sede-vd-validador01 ansible_host=172.17.62.76
sede-vh-glhu ansible_host=172.17.62.71
sede-vh-rnpaghu ansible_host=172.17.62.38
sede-vp-barman ansible_host=172.17.62.22
sede-vp-ntpaghu ansible_host=172.17.62.170
# sede-vp-services01 ansible_host=172.17.62.136
sede-vs-auddb01 ansible_host=172.17.62.90
sede-vs-jkins1 ansible_host=172.17.62.31
sede-vs-memchd1 ansible_host=172.17.62.55
sede-vs-moodle1 ansible_host=172.17.62.32
sede-vs-mysql1 ansible_host=172.17.62.23
# sede-vs-pgaghu11 ansible_host=172.17.62.199
# sede-vs-pgaghu3 ansible_host=172.17.62.177
sede-vs-pgaghurepo ansible_host=172.17.62.35
sede-vs-pgsql1 ansible_host=172.17.62.20
sede-vs-pgsql2 ansible_host=172.17.62.44
sede-vs-prxpor1 ansible_host=172.17.62.80
sede-vs-sig1 ansible_host=172.17.62.14
sede-vt-aghu1 ansible_host=172.17.62.62
sede-vt-aghutreinamento ansible_host=172.17.62.94
sede-vt-apachecldstk ansible_host=172.17.62.235
sede-vt-audpanel1 ansible_host=172.17.62.11
sede-vt-citpgsql1 ansible_host=172.17.62.95
sede-vt-cupsaghud ansible_host=172.17.62.176
# sede-vt-frontend01 ansible_host=172.17.62.224
sede-vt-ged01 ansible_host=172.17.62.140
sede-vt-glpi ansible_host=172.17.62.99
sede-vt-intsis1 ansible_host=172.17.62.27
sede-vt-labdoc1 ansible_host=172.17.62.91
sede-vtl-ens1 ansible_host=172.17.62.143
sede-vtl-rdcap2 ansible_host=172.17.62.87
# sede-vt-mydb ansible_host=172.17.62.182
sede-vt-opsht1 ansible_host=172.17.62.81
sede-vt-opsht10 ansible_host=172.17.62.158
sede-vt-opsht11 ansible_host=172.17.62.159
sede-vt-opsht2 ansible_host=172.17.62.82
sede-vt-opsht3 ansible_host=172.17.62.83
sede-vt-opsht4 ansible_host=172.17.62.147
sede-vt-opsht5 ansible_host=172.17.62.148
sede-vt-opsht6 ansible_host=172.17.62.149
sede-vt-opsht7 ansible_host=172.17.62.152
sede-vt-opsht8 ansible_host=172.17.62.153
sede-vt-opsht9 ansible_host=172.17.62.157
sede-vt-pghost3 ansible_host=172.17.62.67
sede-vt-pgsql_master1 ansible_host=172.17.62.64
sede-vt-pgsql_slave1 ansible_host=172.17.62.65
sede-vt-pgsql_slave2 ansible_host=172.17.62.66
sede-vt-pgsql2 ansible_host=172.17.62.146
sede-vt-psql ansible_host=172.17.62.205
sede-vt-redcap03 ansible_host=172.17.62.41
sede-vt-sig1 ansible_host=172.17.62.15
sede-vt-sig2 ansible_host=172.17.62.18
# sede-vt-superjod01 ansible_host=172.17.62.175
# sede-vt-supermem01 ansible_host=172.17.62.173
# sede-vt-supersolr-1 ansible_host=172.17.62.174
sede-vt-svn1 ansible_host=172.17.62.34
sede-vt-testeaghu ansible_host=172.17.62.47
sede-vt-tgw1 ansible_host=172.17.62.40
sede-vt-verificar-pontos-de-montagem ansible_host=172.17.62.6
# se-dvl-dev1 ansible_host=172.17.62.167
se-dvl-dns1 ansible_host=172.17.62.171
# se-dvl-pgaghu2 ansible_host=172.17.62.50
# se-hvl-api1 ansible_host=172.17.62.129
se-hvl-gfa ansible_host=172.17.62.135
se-hvl-minio1 ansible_host=172.17.62.169
# se-hvl-sicorp ansible_host=172.17.62.120
se-hvl-sisinfra ansible_host=172.17.62.97
# se-hvl-zbxbdm ansible_host=172.17.62.133
se-hvl-zbxpx2 ansible_host=172.17.62.134
# se-hvl-zbxsrv ansible_host=172.17.62.127
se-hvl-zbxweb ansible_host=172.17.62.130
# se-poc-adoc1 ansible_host=172.17.62.180
# se-poc-nix01 ansible_host=172.17.62.74
se-tvl-pgs11 ansible_host=172.17.62.96
